Phase04
Star-Academy/Summer1400-FE-Team5 pull request #3
Opened 2021-08-08 06:14 UTC by IrrfanGhorbani

added js

2021-08-10 14:59 UTC, BijanEisapour requested changes

2021-08-10 14:59 UTC, BijanEisapour commented on build/pages/index.html
> +<html lang="en" dir="rtl">
<div dir='rtl' align='right'>
زبون سایت فارسیه

2021-08-10 14:59 UTC, BijanEisapour commented on build/pages/index.html
> +    <link rel="icon" href="../assets/image/favicon.png" />
<div dir='rtl' align='right'>
این به صورت استاندارد باید پسوندش ico باشه

2021-08-10 14:59 UTC, BijanEisapour commented on .github/workflows/deploy.yml
> +          target-folder: build
<div dir='rtl' align='right'>
نیازی به این کارها نیستو خودِ github pages همینجوری کار میکنه

2021-08-10 14:59 UTC, BijanEisapour commented on build/pages/index.html
> +      <div class="header__background"></div>
<div dir='rtl' align='right'>
واسه یه همچین طرح‌هایی، png به هیچ وجه قابل قبول نیست. باید از svg استفاده کنید. همچنین یه سری از assetهای دیگه مثل لوگو هم باید svg باشه

2021-08-10 14:59 UTC, BijanEisapour commented on build/pages/index.html
> +      </div>
<div dir='rtl' align='right'>
حذف شه

2021-08-10 14:59 UTC, BijanEisapour commented on build/pages/login.html
> +<!DOCTYPE html>
<div dir='rtl' align='right'>
پس‌زمینۀ این صفحه حجمش خیلی زیاده و از طرفی تمرکز رو از کاربر میگیره. حذفش کنید.

2021-08-10 14:59 UTC, BijanEisapour commented on build/pages/login.html
> +<!DOCTYPE html>
<div dir='rtl' align='right'>
همچنین هیچ لینکی به صفحۀ اصلی وجود نداره

2021-08-11 13:05 UTC, IrrfanGhorbani commented on build/pages/index.html
> +<html lang="en" dir="rtl">
:اصلاح شد در 
 434aff2dc5467fef51e280165f3e609f06022386

2021-08-11 13:14 UTC, IrrfanGhorbani commented on build/pages/index.html
> +    <link rel="icon" href="../assets/image/favicon.png" />
اصلاح شد در 
4b00bee1f631a37917660f60c85394f159f2c0d6

2021-08-11 13:17 UTC, IrrfanGhorbani commented on build/pages/index.html
> +      </div>
dca69cae9261a39e3398f9cf7621e4a1783fa386

2021-08-11 14:01 UTC, IrrfanGhorbani commented on build/pages/login.html
> +<!DOCTYPE html>
d4d1dda4bafea6ab32c9cdba059e36ee81494ae9

2021-08-11 14:05 UTC, IrrfanGhorbani commented on build/pages/index.html
> +      <div class="header__background"></div>
عکس را بصورت آماده از دریبل پیدا کردیم و چون متاسفانه فقط در اونجا طرحش بود چاره ای جز استفاده از همین عکس نداشتیم وچون عکسی باحال تر از این پیدا نکردیم مجبور شدیم همینو استفاده کنیم

2021-08-12 15:40 UTC, IrrfanGhorbani commented on .github/workflows/deploy.yml
> +          target-folder: build
ok shod

2021-08-14 11:27 UTC, BijanEisapour approved these changes

2021-08-14 13:07 UTC, merged